packages:
  branch_codenames:
    0.90.13: trusty-unstable
    0.90.13-production: trusty-stable

jobs:
  elasticsearch-ec2:
    builder: make
    base: "quay.io/madebymany/build-bases:trusty"
    apt_keys:
      - "https://apt.mxmdev.com/mxmops.gpg.key"
      - "https://packages.elastic.co/GPG-KEY-elasticsearch"
    apt_repos:
      - "deb https://apt.mxmdev.com stable main"
      - "deb https://packages.elastic.co/elasticsearch/0.90/debian stable main"
    build_depends:
      - openjdk-7-jre-headless
      - elasticsearch=0.90.13
    packages:
      - type: debian
        name: elasticsearch-ec2
        version: 0.90.13-1
        replaces:
          - elasticsearch
        depends:
          - openjdk-7-jre-headless
          - elasticsearch (= 0.90.13)
        target: install
        repos:
          - mxm-public

