packages:
  branch_codenames:
    master: trusty-unstable
    production: trusty-stable

software_groups: &software
  - base

jobs:
  elasticsearch-runit:
    builder: make
    base: "quay.io/madebymany/build-bases:trusty" 
    software_groups: *software
    packages:
      - type: debian
        name: elasticsearch-runit
        version: 0.90.13-2
        depends:
          - libc6
          - runit
          - runit-common
          - openjdk-7-jre-headless
        target: install
        repos:
          - composed-public
  elasticsearch-cloud-aws:
    builder: make
    base: "quay.io/madebymany/build-bases:trusty"
    software_groups: *software
    start_in: elasticsearch-cloud-aws
    packages:
      - type: debian
        name: elasticsearch-cloud-aws
        version: 2.2.0-2
        depends:
          - "elasticsearch-runit (>= 1.2.1-2)"
          - curl
        target: install
        repos:
          - composed-public
