packages:
  branch_codenames:
    0.90.13: trusty-unstable
    0.90.13-production: trusty-stable

jobs:
  elasticsearch-runit:
    builder: make
    base: "quay.io/madebymany/build-bases:trusty"
    build_depends:
      - libc6
      - runit
      - runit-common
      - openjdk-7-jre-headless
    packages:
      - type: debian
        name: elasticsearch-runit
        version: 0.90.13-5
        depends:
          - libc6
          - runit
          - runit-common
          - openjdk-7-jre-headless
        target: install
        repos:
          - mxm-public
  elasticsearch-cloud-aws:
    builder: make
    base: "quay.io/madebymany/build-bases:trusty"
    start_in: elasticsearch-cloud-aws
    packages:
      - type: debian
        name: elasticsearch-cloud-aws
        version: 1.16.0-4
        depends:
          - "elasticsearch-runit (= 0.90.13-5)"
          - "curl"
          - "python-yaml"
        target: install
        repos:
          - mxm-public
