#!/bin/sh

set -e

[ -f /etc/default/elasticsearch ] && . /etc/default/elasticsearch


case "$1" in
  configure)
    [ -z "$ES_USER" ] && ES_USER="elasticsearch"
    [ -z "$ES_GROUP" ] && ES_GROUP="elasticsearch"
    if ! getent group "$ES_GROUP" > /dev/null 2>&1 ; then
      addgroup --system "$ES_GROUP" --quiet
    fi
    if ! id $ES_USER > /dev/null 2>&1 ; then
      adduser --system --home /usr/share/elasticsearch --no-create-home \
	--ingroup "$ES_GROUP" --disabled-password --shell /bin/false \
	"$ES_USER"
    fi

    # Set user permissions on /var/log/elasticsearch and /var/lib/elasticsearch
    mkdir -p /var/log/elasticsearch /var/lib/elasticsearch
    chown -R $ES_USER:$ES_GROUP /var/log/elasticsearch /var/lib/elasticsearch
    chmod 755 /var/log/elasticsearch /var/lib/elasticsearch

    # configuration files should not be modifiable by elasticsearch user, as this can be a security issue
    chown -Rh root:root /etc/elasticsearch/*
    chmod 755 /etc/elasticsearch
    find /etc/elasticsearch -type f -exec chmod 644 {} ';'
    find /etc/elasticsearch -type d -exec chmod 755 {} ';'

    ln -s /etc/sv/elasticsearch /etc/service/elasticsearch

    # if $2 is set, this is an upgrade
    if ( [ -n $2 ] && [ "$RESTART_ON_UPGRADE" = "true" ] ) ; then
      sv -v down elasticsearch
      sv -v up elasticsearch
    fi
    ;;
esac

